// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "bbb-business": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business",
    "method": "GET",
    "path": "/bbb/business",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-business-complaints": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business-complaints",
    "method": "GET",
    "path": "/bbb/business/complaints",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-business-more-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business-more-info",
    "method": "GET",
    "path": "/bbb/business/more-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-business-reviews": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business-reviews",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/business/reviews",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-category": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-category",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/category",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-scamtracker-detail": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-scamtracker-detail",
    "method": "GET",
    "path": "/bbb/scamtracker/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-scamtracker-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-scamtracker-search",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/scamtracker/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "query",
        "type": "string"
      },
      {
        "enum": [
          "Advance Fee Loan",
          "Bank/Credit Card Company Imposter",
          "Business Email Compromise",
          "Charity",
          "Counterfeit Product",
          "COVID-19",
          "Credit Cards",
          "Credit Repair/Debt Relief",
          "CryptoCurrency",
          "Debt Collections",
          "Employment",
          "Fake Check/Money Order",
          "Fake Invoice/Supplier Bill",
          "Family/Friend Emergency",
          "Foreign Money Exchange",
          "Government Agency Imposter",
          "Government Grant",
          "Healthcare/Medicaid/Medicare",
          "Home Improvement",
          "Identity Theft",
          "Investment",
          "Moving",
          "Online Purchase",
          "Other",
          "Phishing",
          "Rental",
          "Retail Business",
          "Romance",
          "Scholarship",
          "Sweepstakes/Lottery/Prizes",
          "Tax Collection",
          "Tech Support",
          "Travel/Vacation/Timeshare",
          "Utility",
          "Vanity Award",
          "Worthless Problem-solving Service",
          "Yellow Pages/Directories"
        ],
        "in": "query",
        "name": "scam_type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "state",
        "type": "string"
      },
      {
        "in": "query",
        "name": "scammer_state",
        "type": "string"
      },
      {
        "in": "query",
        "name": "date_from",
        "type": "string"
      },
      {
        "in": "query",
        "name": "date_to",
        "type": "string"
      },
      {
        "in": "query",
        "name": "min_dollars_lost",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "max_dollars_lost",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-scamtracker-state-stats": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-scamtracker-state-stats",
    "method": "GET",
    "path": "/bbb/scamtracker/state-stats",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "30",
          "90",
          "365",
          "all"
        ],
        "in": "query",
        "name": "period",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-search",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "query",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "location",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "bbb": {
    "business": "bbb-business",
    "businessComplaints": "bbb-business-complaints",
    "businessMoreInfo": "bbb-business-more-info",
    "businessReviews": "bbb-business-reviews",
    "category": "bbb-category",
    "scamtrackerDetail": "bbb-scamtracker-detail",
    "scamtrackerSearch": "bbb-scamtracker-search",
    "scamtrackerStateStats": "bbb-scamtracker-state-stats",
    "search": "bbb-search"
  }
};

export const operationCount = 9;

export const OperationIds = Object.freeze({
  "BbbBusiness": "bbb-business",
  "BbbBusinessComplaints": "bbb-business-complaints",
  "BbbBusinessMoreInfo": "bbb-business-more-info",
  "BbbBusinessReviews": "bbb-business-reviews",
  "BbbCategory": "bbb-category",
  "BbbScamtrackerDetail": "bbb-scamtracker-detail",
  "BbbScamtrackerSearch": "bbb-scamtracker-search",
  "BbbScamtrackerStateStats": "bbb-scamtracker-state-stats",
  "BbbSearch": "bbb-search"
});
