// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "bbb-article": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [],
    "formParams": [],
    "id": "bbb-article",
    "method": "GET",
    "path": "/bbb/article",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-business": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business",
    "method": "GET",
    "path": "/bbb/business",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-business-complaints": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business-complaints",
    "method": "GET",
    "path": "/bbb/business/complaints",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-business-more-info": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business-more-info",
    "method": "GET",
    "path": "/bbb/business/more-info",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-business-reviews": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-business-reviews",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/business/reviews",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-category": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-category",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/category",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "enum": [
          "Relevance",
          "Distance",
          "Rating",
          "AToZ",
          "ZToA"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "5",
          "10",
          "25",
          "50",
          "100"
        ],
        "in": "query",
        "name": "distance",
        "type": "string"
      },
      {
        "collectionFormat": "multi",
        "enum": [
          "A",
          "B",
          "C",
          "D",
          "F"
        ],
        "in": "query",
        "name": "rating",
        "type": "array"
      },
      {
        "collectionFormat": "multi",
        "in": "query",
        "name": "category_id",
        "type": "array"
      },
      {
        "collectionFormat": "multi",
        "in": "query",
        "name": "state",
        "type": "array"
      },
      {
        "in": "query",
        "name": "accredited",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "get_quote",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "service_area",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-local-bbb": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-local-bbb",
    "method": "GET",
    "path": "/bbb/local-bbb",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-local-bbbs": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-local-bbbs",
    "method": "GET",
    "path": "/bbb/local-bbbs",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "us",
          "ca"
        ],
        "in": "query",
        "name": "country",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "region",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-news": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [],
    "formParams": [],
    "id": "bbb-news",
    "method": "GET",
    "path": "/bbb/news",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-news-topics": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [],
    "formParams": [],
    "id": "bbb-news-topics",
    "method": "GET",
    "path": "/bbb/news/topics",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "url",
        "required": true,
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-regions": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-regions",
    "method": "GET",
    "path": "/bbb/regions",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-scamtracker-detail": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-scamtracker-detail",
    "method": "GET",
    "path": "/bbb/scamtracker/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-scamtracker-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-scamtracker-search",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/scamtracker/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "query",
        "type": "string"
      },
      {
        "enum": [
          "Advance Fee Loan",
          "Bank/Credit Card Company Imposter",
          "Business Email Compromise",
          "Charity",
          "Counterfeit Product",
          "COVID-19",
          "Credit Cards",
          "Credit Repair/Debt Relief",
          "CryptoCurrency",
          "Debt Collections",
          "Employment",
          "Fake Check/Money Order",
          "Fake Invoice/Supplier Bill",
          "Family/Friend Emergency",
          "Foreign Money Exchange",
          "Government Agency Imposter",
          "Government Grant",
          "Healthcare/Medicaid/Medicare",
          "Home Improvement",
          "Identity Theft",
          "Investment",
          "Moving",
          "Online Purchase",
          "Other",
          "Phishing",
          "Rental",
          "Retail Business",
          "Romance",
          "Scholarship",
          "Sweepstakes/Lottery/Prizes",
          "Tax Collection",
          "Tech Support",
          "Travel/Vacation/Timeshare",
          "Utility",
          "Vanity Award",
          "Worthless Problem-solving Service",
          "Yellow Pages/Directories"
        ],
        "in": "query",
        "name": "scam_type",
        "type": "string"
      },
      {
        "in": "query",
        "name": "state",
        "type": "string"
      },
      {
        "in": "query",
        "name": "scammer_state",
        "type": "string"
      },
      {
        "in": "query",
        "name": "date_from",
        "type": "string"
      },
      {
        "in": "query",
        "name": "date_to",
        "type": "string"
      },
      {
        "in": "query",
        "name": "min_dollars_lost",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "max_dollars_lost",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-scamtracker-state-stats": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-scamtracker-state-stats",
    "method": "GET",
    "path": "/bbb/scamtracker/state-stats",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "30",
          "90",
          "365",
          "all"
        ],
        "in": "query",
        "name": "period",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-search",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "query",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "location",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "enum": [
          "USA",
          "CAN"
        ],
        "in": "query",
        "name": "country",
        "type": "string"
      },
      {
        "enum": [
          "Relevance",
          "Distance",
          "Rating",
          "AToZ",
          "ZToA"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "5",
          "10",
          "25",
          "50",
          "100"
        ],
        "in": "query",
        "name": "distance",
        "type": "string"
      },
      {
        "collectionFormat": "multi",
        "enum": [
          "A",
          "B",
          "C",
          "D",
          "F"
        ],
        "in": "query",
        "name": "rating",
        "type": "array"
      },
      {
        "collectionFormat": "multi",
        "in": "query",
        "name": "category_id",
        "type": "array"
      },
      {
        "collectionFormat": "multi",
        "in": "query",
        "name": "state",
        "type": "array"
      },
      {
        "in": "query",
        "name": "accredited",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "get_quote",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "service_area",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "bbb-search-filters": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "bbb-search-filters",
    "method": "GET",
    "paginatable": true,
    "path": "/bbb/search/filters",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "query",
        "type": "string"
      },
      {
        "in": "query",
        "name": "location",
        "type": "string"
      },
      {
        "in": "query",
        "name": "category_url",
        "type": "string"
      },
      {
        "enum": [
          "USA",
          "CAN"
        ],
        "in": "query",
        "name": "country",
        "type": "string"
      },
      {
        "in": "query",
        "name": "page",
        "type": "integer"
      },
      {
        "enum": [
          "Relevance",
          "Distance",
          "Rating",
          "AToZ",
          "ZToA"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "5",
          "10",
          "25",
          "50",
          "100"
        ],
        "in": "query",
        "name": "distance",
        "type": "string"
      },
      {
        "collectionFormat": "multi",
        "enum": [
          "A",
          "B",
          "C",
          "D",
          "F"
        ],
        "in": "query",
        "name": "rating",
        "type": "array"
      },
      {
        "collectionFormat": "multi",
        "in": "query",
        "name": "category_id",
        "type": "array"
      },
      {
        "collectionFormat": "multi",
        "in": "query",
        "name": "state",
        "type": "array"
      },
      {
        "in": "query",
        "name": "accredited",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "get_quote",
        "type": "boolean"
      },
      {
        "in": "query",
        "name": "service_area",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "bbb": {
    "article": "bbb-article",
    "business": "bbb-business",
    "businessComplaints": "bbb-business-complaints",
    "businessMoreInfo": "bbb-business-more-info",
    "businessReviews": "bbb-business-reviews",
    "category": "bbb-category",
    "localBbb": "bbb-local-bbb",
    "localBbbs": "bbb-local-bbbs",
    "news": "bbb-news",
    "newsTopics": "bbb-news-topics",
    "regions": "bbb-regions",
    "scamtrackerDetail": "bbb-scamtracker-detail",
    "scamtrackerSearch": "bbb-scamtracker-search",
    "scamtrackerStateStats": "bbb-scamtracker-state-stats",
    "search": "bbb-search",
    "searchFilters": "bbb-search-filters"
  }
};

export const operationCount = 16;

export const OperationIds = Object.freeze({
  "BbbArticle": "bbb-article",
  "BbbBusiness": "bbb-business",
  "BbbBusinessComplaints": "bbb-business-complaints",
  "BbbBusinessMoreInfo": "bbb-business-more-info",
  "BbbBusinessReviews": "bbb-business-reviews",
  "BbbCategory": "bbb-category",
  "BbbLocalBbb": "bbb-local-bbb",
  "BbbLocalBbbs": "bbb-local-bbbs",
  "BbbNews": "bbb-news",
  "BbbNewsTopics": "bbb-news-topics",
  "BbbRegions": "bbb-regions",
  "BbbScamtrackerDetail": "bbb-scamtracker-detail",
  "BbbScamtrackerSearch": "bbb-scamtracker-search",
  "BbbScamtrackerStateStats": "bbb-scamtracker-state-stats",
  "BbbSearch": "bbb-search",
  "BbbSearchFilters": "bbb-search-filters"
});
