// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelBbbSearchFiltersResponseDoc {
  "code"?: number;
  "data"?: ModelBbbSearchFiltersResponse;
  "msg"?: string;
}

export interface ModelBbbSearchFiltersResponse {
  "categories"?: Array<ModelBbbSearchFilterValue>;
  "country"?: "USA" | "CAN";
  "location"?: string;
  "page"?: number;
  "query"?: string;
  "sorts"?: Array<ModelBbbSearchSortOption>;
  "states"?: Array<ModelBbbSearchFilterValue>;
  "total_results"?: number;
}

export interface ModelBbbSearchFilterValue {
  "label"?: string;
  "value"?: string;
}

export interface ModelBbbSearchSortOption {
  "is_active"?: boolean;
  "label"?: string;
  "value"?: "Relevance" | "Distance" | "Rating" | "AToZ" | "ZToA";
}

export interface ModelBbbSearchResponseDoc {
  "code"?: number;
  "data"?: ModelBbbSearchResponse;
  "msg"?: string;
}

export interface ModelBbbSearchResponse {
  "location"?: string;
  "page"?: number;
  "query"?: string;
  "related_categories"?: Array<ModelBbbRelatedCategory>;
  "results"?: Array<ModelBbbBusinessSearchResult>;
  "source_url"?: string;
  "total_results"?: number;
}

export interface ModelBbbBusinessSearchResult {
  "accredited"?: boolean;
  "address"?: string;
  "categories"?: Array<string>;
  "hq_profile_url"?: string;
  "image_url"?: string;
  "name"?: string;
  "phone"?: string;
  "quote_url"?: string;
  "rating"?: string;
  "service_areas"?: Array<string>;
  "url"?: string;
}

export interface ModelBbbRelatedCategory {
  "name"?: string;
  "url"?: string;
}

export interface ModelBbbscamtrackerDetailResponseDoc {
  "code"?: number;
  "data"?: ModelBbbscamtrackerDetailResponse;
  "msg"?: string;
}

export interface ModelBbbscamtrackerDetailResponse {
  "business_name"?: string;
  "date_reported"?: string;
  "description"?: string;
  "dollars_lost"?: string;
  "id"?: string;
  "scam_type"?: string;
  "scammer_email"?: string;
  "scammer_location"?: string;
  "scammer_phone"?: string;
  "scammer_url"?: string;
  "source_url"?: string;
  "targeted_location"?: string;
}

export interface ModelBbbscamtrackerStateStatsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbscamtrackerStateStatsResponse;
  "msg"?: string;
}

export interface ModelBbbscamtrackerStateStatsResponse {
  "aggregated_at"?: string;
  "period"?: string;
  "states"?: Array<ModelBbbscamtrackerStateStat>;
}

export interface ModelBbbscamtrackerStateStat {
  "code"?: string;
  "country"?: string;
  "losses"?: number;
  "losses_per_capita"?: number;
  "median_loss"?: number;
  "name"?: string;
  "pct_reporting_loss"?: number;
  "population"?: number;
  "reports"?: number;
  "reports_per_capita"?: number;
  "reports_with_loss"?: number;
  "scam_type_breakdown"?: Array<ModelBbbscamtrackerScamTypeShare>;
  "top_scam_type"?: string;
  "yoy_change_pct"?: number;
}

export interface ModelBbbscamtrackerScamTypeShare {
  "count"?: number;
  "pct"?: number;
  "type"?: string;
}

export interface ModelBbbscamtrackerSearchResponseDoc {
  "code"?: number;
  "data"?: ModelBbbscamtrackerSearchResponse;
  "msg"?: string;
}

export interface ModelBbbscamtrackerSearchResponse {
  "date_from"?: string;
  "date_to"?: string;
  "max_dollars_lost"?: number;
  "min_dollars_lost"?: number;
  "page"?: number;
  "query"?: string;
  "results"?: Array<ModelBbbscamtrackerScamResult>;
  "scam_type"?: string;
  "scammer_state"?: string;
  "source_url"?: string;
  "state"?: string;
  "total_results"?: number;
  "total_results_lower_bound"?: boolean;
}

export interface ModelBbbscamtrackerScamResult {
  "business_name_used"?: string;
  "category"?: string;
  "date_reported"?: string;
  "description"?: string;
  "dollars_lost"?: string;
  "id"?: string;
  "url"?: string;
  "victim_location"?: string;
}

export interface ModelBbbdirectoryRegionsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbdirectoryRegionsResponse;
  "msg"?: string;
}

export interface ModelBbbdirectoryRegionsResponse {
  "countries"?: Array<ModelBbbdirectoryCountryRegions>;
}

export interface ModelBbbdirectoryCountryRegions {
  "code"?: string;
  "name"?: string;
  "regions"?: Array<ModelBbbdirectoryRegionOption>;
}

export interface ModelBbbdirectoryRegionOption {
  "code"?: string;
  "name"?: string;
  "url"?: string;
}

export interface ModelBbbnewsTopicsResponse {
  "country"?: string;
  "source_url"?: string;
  "topics"?: Array<ModelBbbnewsTopic>;
}

export interface ModelBbbnewsTopic {
  "name"?: string;
  "slug"?: string;
  "url"?: string;
}

export interface ModelBbbnewsNewsResponse {
  "country"?: string;
  "items"?: Array<ModelBbbnewsNewsItem>;
  "page"?: number;
  "page_size"?: number;
  "source_url"?: string;
  "topic"?: string;
  "total"?: number;
}

export interface ModelBbbnewsNewsItem {
  "event_start_date"?: string;
  "event_url"?: string;
  "id"?: string;
  "image"?: ModelBbbnewsImage;
  "modified_date"?: string;
  "summary"?: string;
  "title"?: string;
  "type"?: string;
  "url"?: string;
}

export interface ModelBbbnewsImage {
  "alt_text"?: string;
  "caption"?: string;
  "credit"?: string;
  "url"?: string;
}

export interface ModelBbbdirectoryLocalBbbsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbdirectoryLocalBbbsResponse;
  "msg"?: string;
}

export interface ModelBbbdirectoryLocalBbbsResponse {
  "chapters"?: Array<ModelBbbdirectoryLocalBbbchapter>;
  "country"?: string;
  "region"?: ModelBbbdirectoryRegionOption;
}

export interface ModelBbbdirectoryLocalBbbchapter {
  "id"?: string;
  "name"?: string;
  "offices"?: Array<ModelBbbdirectoryOffice>;
  "open_to_public"?: boolean;
  "url"?: string;
}

export interface ModelBbbdirectoryOffice {
  "address"?: ModelBbbdirectoryOfficeAddress;
  "contact"?: ModelBbbdirectoryOfficeContact;
  "formatted_address"?: string;
  "is_primary"?: boolean;
  "jurisdictions"?: Array<string>;
  "office_hours"?: Array<string>;
  "phone_hours"?: Array<string>;
  "type"?: string;
}

export interface ModelBbbdirectoryOfficeContact {
  "email"?: string;
  "fax_number"?: string;
  "phone_number"?: string;
}

export interface ModelBbbdirectoryOfficeAddress {
  "city"?: string;
  "country"?: string;
  "county"?: string;
  "line1"?: string;
  "line2"?: string;
  "location_name"?: string;
  "postal_code"?: string;
  "state_province"?: string;
}

export interface ModelBbbdirectoryLocalBbbresponseDoc {
  "code"?: number;
  "data"?: ModelBbbdirectoryLocalBbbresponse;
  "msg"?: string;
}

export interface ModelBbbdirectoryLocalBbbresponse {
  "about"?: string;
  "events"?: Array<ModelBbbdirectoryBbbevent>;
  "id"?: string;
  "languages"?: Array<string>;
  "name"?: string;
  "offices"?: Array<ModelBbbdirectoryOffice>;
  "open_to_public"?: boolean;
  "service_territory"?: Array<string>;
  "tagline"?: string;
  "url"?: string;
}

export interface ModelBbbdirectoryBbbevent {
  "ends_at"?: string;
  "starts_at"?: string;
  "summary"?: string;
  "title"?: string;
  "url"?: string;
}

export interface ModelBbbCategoryResponseDoc {
  "code"?: number;
  "data"?: ModelBbbCategoryResponse;
  "msg"?: string;
}

export interface ModelBbbCategoryResponse {
  "page"?: number;
  "results"?: Array<ModelBbbBusinessSearchResult>;
  "source_url"?: string;
  "total_results"?: number;
}

export interface ModelBbbReviewsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbReviewsResponse;
  "msg"?: string;
}

export interface ModelBbbReviewsResponse {
  "average_rating"?: number;
  "page"?: number;
  "reviews"?: Array<ModelBbbReviewItem>;
  "source_url"?: string;
  "total_pages"?: number;
  "total_reviews"?: number;
}

export interface ModelBbbReviewItem {
  "author"?: string;
  "date"?: string;
  "id"?: string;
  "rating"?: number;
  "responses"?: Array<ModelBbbReviewResponse>;
  "text"?: string;
}

export interface ModelBbbReviewResponse {
  "date"?: string;
  "is_business"?: boolean;
  "text"?: string;
  "title"?: string;
}

export interface ModelBbbMoreInfoResponseDoc {
  "code"?: number;
  "data"?: ModelBbbMoreInfoResponse;
  "msg"?: string;
}

export interface ModelBbbMoreInfoResponse {
  "business_name"?: string;
  "rating"?: string;
  "rating_reasons"?: Array<string>;
  "service_areas"?: Array<string>;
  "source_url"?: string;
}

export interface ModelBbbComplaintsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbComplaintsResponse;
  "msg"?: string;
}

export interface ModelBbbComplaintsResponse {
  "business_name"?: string;
  "closed_last_12_months"?: number;
  "complaints"?: Array<ModelBbbComplaint>;
  "complaints_list_incomplete"?: boolean;
  "period_text"?: string;
  "source_url"?: string;
  "submit_complaint_url"?: string;
  "total_complaints"?: number;
}

export interface ModelBbbComplaint {
  "business_responses"?: Array<ModelBbbComplaintMessage>;
  "customer_answers"?: Array<ModelBbbComplaintMessage>;
  "date"?: string;
  "id"?: string;
  "status"?: string;
  "text"?: string;
  "type"?: string;
}

export interface ModelBbbComplaintMessage {
  "date"?: string;
  "text"?: string;
}

export interface ModelBbbBusinessResponseDoc {
  "code"?: number;
  "data"?: ModelBbbBusinessResponse;
  "msg"?: string;
}

export interface ModelBbbBusinessResponse {
  "accredited"?: boolean;
  "accredited_since"?: string;
  "additional_phone_numbers"?: Array<string>;
  "additional_websites"?: Array<string>;
  "address"?: string;
  "alternate_names"?: Array<string>;
  "bbb_file_opened"?: string;
  "business_incorporated"?: string;
  "business_management"?: string;
  "business_started"?: string;
  "categories"?: Array<string>;
  "category"?: string;
  "entity_type"?: string;
  "hours"?: Array<ModelBbbBusinessHoursDay>;
  "image_url"?: string;
  "latest_reviews"?: Array<ModelBbbReviewPreview>;
  "licensing_note"?: string;
  "local_bbb"?: string;
  "local_bbb_url"?: string;
  "more_info_url"?: string;
  "name"?: string;
  "phone"?: string;
  "products_and_services"?: Array<string>;
  "rating"?: string;
  "rating_reasons"?: Array<string>;
  "social_media"?: Array<string>;
  "source_url"?: string;
  "url"?: string;
  "website"?: string;
  "years_in_business"?: string;
}

export interface ModelBbbReviewPreview {
  "author"?: string;
  "quote"?: string;
  "url"?: string;
}

export interface ModelBbbBusinessHoursDay {
  "day"?: string;
  "hours"?: string;
}

export interface ModelBbbnewsArticleResponse {
  "authors"?: Array<ModelBbbnewsAuthor>;
  "body"?: string;
  "id"?: string;
  "image"?: ModelBbbnewsImage;
  "links"?: Array<ModelBbbnewsLink>;
  "modified_at"?: string;
  "published_at"?: string;
  "source_url"?: string;
  "summary"?: string;
  "title"?: string;
  "topics"?: Array<string>;
  "type"?: string;
}

export interface ModelBbbnewsLink {
  "text"?: string;
  "url"?: string;
}

export interface ModelBbbnewsAuthor {
  "name"?: string;
  "url"?: string;
}

export type BbbArticleResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelBbbnewsArticleResponse }>;
export interface BbbArticleParams {
  "url": string;
}

export type BbbBusinessResponse = CrawloraResponse<ModelBbbBusinessResponseDoc>;
export interface BbbBusinessParams {
  "url": string;
}

export type BbbBusinessComplaintsResponse = CrawloraResponse<ModelBbbComplaintsResponseDoc>;
export interface BbbBusinessComplaintsParams {
  "url": string;
}

export type BbbBusinessMoreInfoResponse = CrawloraResponse<ModelBbbMoreInfoResponseDoc>;
export interface BbbBusinessMoreInfoParams {
  "url": string;
}

export type BbbBusinessReviewsResponse = CrawloraResponse<ModelBbbReviewsResponseDoc>;
export interface BbbBusinessReviewsParams {
  "url": string;
  "page"?: number;
}

export type BbbCategoryResponse = CrawloraResponse<ModelBbbCategoryResponseDoc>;
export interface BbbCategoryParams {
  "url": string;
  "page"?: number;
  "sort"?: "Relevance" | "Distance" | "Rating" | "AToZ" | "ZToA";
  "distance"?: "5" | "10" | "25" | "50" | "100";
  "rating"?: Array<"A" | "B" | "C" | "D" | "F">;
  "category_id"?: Array<string>;
  "state"?: Array<string>;
  "accredited"?: boolean;
  "get_quote"?: boolean;
  "service_area"?: boolean;
}

export type BbbLocalBbbResponse = CrawloraResponse<ModelBbbdirectoryLocalBbbresponseDoc>;
export interface BbbLocalBbbParams {
  "url": string;
}

export type BbbLocalBbbsResponse = CrawloraResponse<ModelBbbdirectoryLocalBbbsResponseDoc>;
export interface BbbLocalBbbsParams {
  "country": "us" | "ca";
  "region": string;
}

export type BbbNewsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelBbbnewsNewsResponse }>;
export interface BbbNewsParams {
  "url": string;
}

export type BbbNewsTopicsResponse = CrawloraResponse<ModelAppResponse & { "data"?: ModelBbbnewsTopicsResponse }>;
export interface BbbNewsTopicsParams {
  "url": string;
}

export type BbbRegionsResponse = CrawloraResponse<ModelBbbdirectoryRegionsResponseDoc>;
export interface BbbRegionsParams {
}

export type BbbScamtrackerSearchResponse = CrawloraResponse<ModelBbbscamtrackerSearchResponseDoc>;
export interface BbbScamtrackerSearchParams {
  "query"?: string;
  "scam_type"?: "Advance Fee Loan" | "Bank/Credit Card Company Imposter" | "Business Email Compromise" | "Charity" | "Counterfeit Product" | "COVID-19" | "Credit Cards" | "Credit Repair/Debt Relief" | "CryptoCurrency" | "Debt Collections" | "Employment" | "Fake Check/Money Order" | "Fake Invoice/Supplier Bill" | "Family/Friend Emergency" | "Foreign Money Exchange" | "Government Agency Imposter" | "Government Grant" | "Healthcare/Medicaid/Medicare" | "Home Improvement" | "Identity Theft" | "Investment" | "Moving" | "Online Purchase" | "Other" | "Phishing" | "Rental" | "Retail Business" | "Romance" | "Scholarship" | "Sweepstakes/Lottery/Prizes" | "Tax Collection" | "Tech Support" | "Travel/Vacation/Timeshare" | "Utility" | "Vanity Award" | "Worthless Problem-solving Service" | "Yellow Pages/Directories";
  "state"?: string;
  "scammer_state"?: string;
  "date_from"?: string;
  "date_to"?: string;
  "min_dollars_lost"?: number;
  "max_dollars_lost"?: number;
  "page"?: number;
}

export type BbbScamtrackerStateStatsResponse = CrawloraResponse<ModelBbbscamtrackerStateStatsResponseDoc>;
export interface BbbScamtrackerStateStatsParams {
  "period"?: "30" | "90" | "365" | "all";
}

export type BbbScamtrackerDetailResponse = CrawloraResponse<ModelBbbscamtrackerDetailResponseDoc>;
export interface BbbScamtrackerDetailParams {
  "id": string;
}

export type BbbSearchResponse = CrawloraResponse<ModelBbbSearchResponseDoc>;
export interface BbbSearchParams {
  "query": string;
  "location": string;
  "page"?: number;
  "country"?: "USA" | "CAN";
  "sort"?: "Relevance" | "Distance" | "Rating" | "AToZ" | "ZToA";
  "distance"?: "5" | "10" | "25" | "50" | "100";
  "rating"?: Array<"A" | "B" | "C" | "D" | "F">;
  "category_id"?: Array<string>;
  "state"?: Array<string>;
  "accredited"?: boolean;
  "get_quote"?: boolean;
  "service_area"?: boolean;
}

export type BbbSearchFiltersResponse = CrawloraResponse<ModelBbbSearchFiltersResponseDoc>;
export interface BbbSearchFiltersParams {
  "query"?: string;
  "location"?: string;
  "category_url"?: string;
  "country"?: "USA" | "CAN";
  "page"?: number;
  "sort"?: "Relevance" | "Distance" | "Rating" | "AToZ" | "ZToA";
  "distance"?: "5" | "10" | "25" | "50" | "100";
  "rating"?: Array<"A" | "B" | "C" | "D" | "F">;
  "category_id"?: Array<string>;
  "state"?: Array<string>;
  "accredited"?: boolean;
  "get_quote"?: boolean;
  "service_area"?: boolean;
}

export interface BbbService {
  article<T = BbbArticleResponse>(params: BbbArticleParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  business<T = BbbBusinessResponse>(params: BbbBusinessParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  businessComplaints<T = BbbBusinessComplaintsResponse>(params: BbbBusinessComplaintsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  businessMoreInfo<T = BbbBusinessMoreInfoResponse>(params: BbbBusinessMoreInfoParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  businessReviews<T = BbbBusinessReviewsResponse>(params: BbbBusinessReviewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  category<T = BbbCategoryResponse>(params: BbbCategoryParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  localBbb<T = BbbLocalBbbResponse>(params: BbbLocalBbbParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  localBbbs<T = BbbLocalBbbsResponse>(params: BbbLocalBbbsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  news<T = BbbNewsResponse>(params: BbbNewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  newsTopics<T = BbbNewsTopicsResponse>(params: BbbNewsTopicsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  regions<T = BbbRegionsResponse>(params?: BbbRegionsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scamtrackerSearch<T = BbbScamtrackerSearchResponse>(params?: BbbScamtrackerSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scamtrackerStateStats<T = BbbScamtrackerStateStatsResponse>(params?: BbbScamtrackerStateStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scamtrackerDetail<T = BbbScamtrackerDetailResponse>(params: BbbScamtrackerDetailParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = BbbSearchResponse>(params: BbbSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  searchFilters<T = BbbSearchFiltersResponse>(params?: BbbSearchFiltersParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  bbb: BbbService;
}

export interface OperationParamsMap {
  "bbb-article": BbbArticleParams;
  "bbb-business": BbbBusinessParams;
  "bbb-business-complaints": BbbBusinessComplaintsParams;
  "bbb-business-more-info": BbbBusinessMoreInfoParams;
  "bbb-business-reviews": BbbBusinessReviewsParams;
  "bbb-category": BbbCategoryParams;
  "bbb-local-bbb": BbbLocalBbbParams;
  "bbb-local-bbbs": BbbLocalBbbsParams;
  "bbb-news": BbbNewsParams;
  "bbb-news-topics": BbbNewsTopicsParams;
  "bbb-regions": BbbRegionsParams;
  "bbb-scamtracker-search": BbbScamtrackerSearchParams;
  "bbb-scamtracker-state-stats": BbbScamtrackerStateStatsParams;
  "bbb-scamtracker-detail": BbbScamtrackerDetailParams;
  "bbb-search": BbbSearchParams;
  "bbb-search-filters": BbbSearchFiltersParams;
}

export interface OperationResponseMap {
  "bbb-article": BbbArticleResponse;
  "bbb-business": BbbBusinessResponse;
  "bbb-business-complaints": BbbBusinessComplaintsResponse;
  "bbb-business-more-info": BbbBusinessMoreInfoResponse;
  "bbb-business-reviews": BbbBusinessReviewsResponse;
  "bbb-category": BbbCategoryResponse;
  "bbb-local-bbb": BbbLocalBbbResponse;
  "bbb-local-bbbs": BbbLocalBbbsResponse;
  "bbb-news": BbbNewsResponse;
  "bbb-news-topics": BbbNewsTopicsResponse;
  "bbb-regions": BbbRegionsResponse;
  "bbb-scamtracker-search": BbbScamtrackerSearchResponse;
  "bbb-scamtracker-state-stats": BbbScamtrackerStateStatsResponse;
  "bbb-scamtracker-detail": BbbScamtrackerDetailResponse;
  "bbb-search": BbbSearchResponse;
  "bbb-search-filters": BbbSearchFiltersResponse;
}

export interface OperationRequiredParamsMap {
  "bbb-article": true;
  "bbb-business": true;
  "bbb-business-complaints": true;
  "bbb-business-more-info": true;
  "bbb-business-reviews": true;
  "bbb-category": true;
  "bbb-local-bbb": true;
  "bbb-local-bbbs": true;
  "bbb-news": true;
  "bbb-news-topics": true;
  "bbb-regions": false;
  "bbb-scamtracker-search": false;
  "bbb-scamtracker-state-stats": false;
  "bbb-scamtracker-detail": true;
  "bbb-search": true;
  "bbb-search-filters": false;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "bbb-article"
  | "bbb-business"
  | "bbb-business-complaints"
  | "bbb-business-more-info"
  | "bbb-business-reviews"
  | "bbb-category"
  | "bbb-local-bbb"
  | "bbb-local-bbbs"
  | "bbb-news"
  | "bbb-news-topics"
  | "bbb-regions"
  | "bbb-scamtracker-search"
  | "bbb-scamtracker-state-stats"
  | "bbb-scamtracker-detail"
  | "bbb-search"
  | "bbb-search-filters";

export declare const OperationIds: Readonly<{
  BbbArticle: "bbb-article";
  BbbBusiness: "bbb-business";
  BbbBusinessComplaints: "bbb-business-complaints";
  BbbBusinessMoreInfo: "bbb-business-more-info";
  BbbBusinessReviews: "bbb-business-reviews";
  BbbCategory: "bbb-category";
  BbbLocalBbb: "bbb-local-bbb";
  BbbLocalBbbs: "bbb-local-bbbs";
  BbbNews: "bbb-news";
  BbbNewsTopics: "bbb-news-topics";
  BbbRegions: "bbb-regions";
  BbbScamtrackerDetail: "bbb-scamtracker-detail";
  BbbScamtrackerSearch: "bbb-scamtracker-search";
  BbbScamtrackerStateStats: "bbb-scamtracker-state-stats";
  BbbSearch: "bbb-search";
  BbbSearchFilters: "bbb-search-filters";
}>;
