// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelBbbSearchResponseDoc {
  "code"?: number;
  "data"?: ModelBbbSearchResponse;
  "msg"?: string;
}

export interface ModelBbbSearchResponse {
  "location"?: string;
  "page"?: number;
  "query"?: string;
  "related_categories"?: Array<ModelBbbRelatedCategory>;
  "results"?: Array<ModelBbbBusinessSearchResult>;
  "source_url"?: string;
  "total_results"?: number;
}

export interface ModelBbbBusinessSearchResult {
  "accredited"?: boolean;
  "address"?: string;
  "categories"?: Array<string>;
  "hq_profile_url"?: string;
  "image_url"?: string;
  "name"?: string;
  "phone"?: string;
  "quote_url"?: string;
  "rating"?: string;
  "service_areas"?: Array<string>;
  "url"?: string;
}

export interface ModelBbbRelatedCategory {
  "name"?: string;
  "url"?: string;
}

export interface ModelBbbscamtrackerDetailResponseDoc {
  "code"?: number;
  "data"?: ModelBbbscamtrackerDetailResponse;
  "msg"?: string;
}

export interface ModelBbbscamtrackerDetailResponse {
  "business_name"?: string;
  "date_reported"?: string;
  "description"?: string;
  "dollars_lost"?: string;
  "id"?: string;
  "scam_type"?: string;
  "scammer_email"?: string;
  "scammer_location"?: string;
  "scammer_phone"?: string;
  "scammer_url"?: string;
  "source_url"?: string;
  "targeted_location"?: string;
}

export interface ModelBbbscamtrackerStateStatsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbscamtrackerStateStatsResponse;
  "msg"?: string;
}

export interface ModelBbbscamtrackerStateStatsResponse {
  "aggregated_at"?: string;
  "period"?: string;
  "states"?: Array<ModelBbbscamtrackerStateStat>;
}

export interface ModelBbbscamtrackerStateStat {
  "code"?: string;
  "country"?: string;
  "losses"?: number;
  "losses_per_capita"?: number;
  "median_loss"?: number;
  "name"?: string;
  "pct_reporting_loss"?: number;
  "population"?: number;
  "reports"?: number;
  "reports_per_capita"?: number;
  "reports_with_loss"?: number;
  "scam_type_breakdown"?: Array<ModelBbbscamtrackerScamTypeShare>;
  "top_scam_type"?: string;
  "yoy_change_pct"?: number;
}

export interface ModelBbbscamtrackerScamTypeShare {
  "count"?: number;
  "pct"?: number;
  "type"?: string;
}

export interface ModelBbbscamtrackerSearchResponseDoc {
  "code"?: number;
  "data"?: ModelBbbscamtrackerSearchResponse;
  "msg"?: string;
}

export interface ModelBbbscamtrackerSearchResponse {
  "date_from"?: string;
  "date_to"?: string;
  "max_dollars_lost"?: number;
  "min_dollars_lost"?: number;
  "page"?: number;
  "query"?: string;
  "results"?: Array<ModelBbbscamtrackerScamResult>;
  "scam_type"?: string;
  "scammer_state"?: string;
  "source_url"?: string;
  "state"?: string;
  "total_results"?: number;
  "total_results_lower_bound"?: boolean;
}

export interface ModelBbbscamtrackerScamResult {
  "business_name_used"?: string;
  "category"?: string;
  "date_reported"?: string;
  "description"?: string;
  "dollars_lost"?: string;
  "id"?: string;
  "url"?: string;
  "victim_location"?: string;
}

export interface ModelBbbCategoryResponseDoc {
  "code"?: number;
  "data"?: ModelBbbCategoryResponse;
  "msg"?: string;
}

export interface ModelBbbCategoryResponse {
  "page"?: number;
  "results"?: Array<ModelBbbBusinessSearchResult>;
  "source_url"?: string;
  "total_results"?: number;
}

export interface ModelBbbReviewsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbReviewsResponse;
  "msg"?: string;
}

export interface ModelBbbReviewsResponse {
  "average_rating"?: number;
  "page"?: number;
  "reviews"?: Array<ModelBbbReviewItem>;
  "source_url"?: string;
  "total_pages"?: number;
  "total_reviews"?: number;
}

export interface ModelBbbReviewItem {
  "author"?: string;
  "date"?: string;
  "id"?: string;
  "rating"?: number;
  "responses"?: Array<ModelBbbReviewResponse>;
  "text"?: string;
}

export interface ModelBbbReviewResponse {
  "date"?: string;
  "is_business"?: boolean;
  "text"?: string;
  "title"?: string;
}

export interface ModelBbbMoreInfoResponseDoc {
  "code"?: number;
  "data"?: ModelBbbMoreInfoResponse;
  "msg"?: string;
}

export interface ModelBbbMoreInfoResponse {
  "business_name"?: string;
  "rating"?: string;
  "rating_reasons"?: Array<string>;
  "service_areas"?: Array<string>;
  "source_url"?: string;
}

export interface ModelBbbComplaintsResponseDoc {
  "code"?: number;
  "data"?: ModelBbbComplaintsResponse;
  "msg"?: string;
}

export interface ModelBbbComplaintsResponse {
  "business_name"?: string;
  "closed_last_12_months"?: number;
  "complaints"?: Array<ModelBbbComplaint>;
  "complaints_list_incomplete"?: boolean;
  "period_text"?: string;
  "source_url"?: string;
  "submit_complaint_url"?: string;
  "total_complaints"?: number;
}

export interface ModelBbbComplaint {
  "business_responses"?: Array<ModelBbbComplaintMessage>;
  "customer_answers"?: Array<ModelBbbComplaintMessage>;
  "date"?: string;
  "id"?: string;
  "status"?: string;
  "text"?: string;
  "type"?: string;
}

export interface ModelBbbComplaintMessage {
  "date"?: string;
  "text"?: string;
}

export interface ModelBbbBusinessResponseDoc {
  "code"?: number;
  "data"?: ModelBbbBusinessResponse;
  "msg"?: string;
}

export interface ModelBbbBusinessResponse {
  "accredited"?: boolean;
  "accredited_since"?: string;
  "additional_phone_numbers"?: Array<string>;
  "additional_websites"?: Array<string>;
  "address"?: string;
  "alternate_names"?: Array<string>;
  "bbb_file_opened"?: string;
  "business_incorporated"?: string;
  "business_management"?: string;
  "business_started"?: string;
  "categories"?: Array<string>;
  "category"?: string;
  "entity_type"?: string;
  "hours"?: Array<ModelBbbBusinessHoursDay>;
  "image_url"?: string;
  "latest_reviews"?: Array<ModelBbbReviewPreview>;
  "licensing_note"?: string;
  "local_bbb"?: string;
  "local_bbb_url"?: string;
  "more_info_url"?: string;
  "name"?: string;
  "phone"?: string;
  "products_and_services"?: Array<string>;
  "rating"?: string;
  "rating_reasons"?: Array<string>;
  "social_media"?: Array<string>;
  "source_url"?: string;
  "url"?: string;
  "website"?: string;
  "years_in_business"?: string;
}

export interface ModelBbbReviewPreview {
  "author"?: string;
  "quote"?: string;
  "url"?: string;
}

export interface ModelBbbBusinessHoursDay {
  "day"?: string;
  "hours"?: string;
}

export type BbbBusinessResponse = CrawloraResponse<ModelBbbBusinessResponseDoc>;
export interface BbbBusinessParams {
  "url": string;
}

export type BbbBusinessComplaintsResponse = CrawloraResponse<ModelBbbComplaintsResponseDoc>;
export interface BbbBusinessComplaintsParams {
  "url": string;
}

export type BbbBusinessMoreInfoResponse = CrawloraResponse<ModelBbbMoreInfoResponseDoc>;
export interface BbbBusinessMoreInfoParams {
  "url": string;
}

export type BbbBusinessReviewsResponse = CrawloraResponse<ModelBbbReviewsResponseDoc>;
export interface BbbBusinessReviewsParams {
  "url": string;
  "page"?: number;
}

export type BbbCategoryResponse = CrawloraResponse<ModelBbbCategoryResponseDoc>;
export interface BbbCategoryParams {
  "url": string;
  "page"?: number;
}

export type BbbScamtrackerSearchResponse = CrawloraResponse<ModelBbbscamtrackerSearchResponseDoc>;
export interface BbbScamtrackerSearchParams {
  "query"?: string;
  "scam_type"?: "Advance Fee Loan" | "Bank/Credit Card Company Imposter" | "Business Email Compromise" | "Charity" | "Counterfeit Product" | "COVID-19" | "Credit Cards" | "Credit Repair/Debt Relief" | "CryptoCurrency" | "Debt Collections" | "Employment" | "Fake Check/Money Order" | "Fake Invoice/Supplier Bill" | "Family/Friend Emergency" | "Foreign Money Exchange" | "Government Agency Imposter" | "Government Grant" | "Healthcare/Medicaid/Medicare" | "Home Improvement" | "Identity Theft" | "Investment" | "Moving" | "Online Purchase" | "Other" | "Phishing" | "Rental" | "Retail Business" | "Romance" | "Scholarship" | "Sweepstakes/Lottery/Prizes" | "Tax Collection" | "Tech Support" | "Travel/Vacation/Timeshare" | "Utility" | "Vanity Award" | "Worthless Problem-solving Service" | "Yellow Pages/Directories";
  "state"?: string;
  "scammer_state"?: string;
  "date_from"?: string;
  "date_to"?: string;
  "min_dollars_lost"?: number;
  "max_dollars_lost"?: number;
  "page"?: number;
}

export type BbbScamtrackerStateStatsResponse = CrawloraResponse<ModelBbbscamtrackerStateStatsResponseDoc>;
export interface BbbScamtrackerStateStatsParams {
  "period"?: "30" | "90" | "365" | "all";
}

export type BbbScamtrackerDetailResponse = CrawloraResponse<ModelBbbscamtrackerDetailResponseDoc>;
export interface BbbScamtrackerDetailParams {
  "id": string;
}

export type BbbSearchResponse = CrawloraResponse<ModelBbbSearchResponseDoc>;
export interface BbbSearchParams {
  "query": string;
  "location": string;
  "page"?: number;
}

export interface BbbService {
  business<T = BbbBusinessResponse>(params: BbbBusinessParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  businessComplaints<T = BbbBusinessComplaintsResponse>(params: BbbBusinessComplaintsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  businessMoreInfo<T = BbbBusinessMoreInfoResponse>(params: BbbBusinessMoreInfoParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  businessReviews<T = BbbBusinessReviewsResponse>(params: BbbBusinessReviewsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  category<T = BbbCategoryResponse>(params: BbbCategoryParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scamtrackerSearch<T = BbbScamtrackerSearchResponse>(params?: BbbScamtrackerSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scamtrackerStateStats<T = BbbScamtrackerStateStatsResponse>(params?: BbbScamtrackerStateStatsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  scamtrackerDetail<T = BbbScamtrackerDetailResponse>(params: BbbScamtrackerDetailParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = BbbSearchResponse>(params: BbbSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  bbb: BbbService;
}

export interface OperationParamsMap {
  "bbb-business": BbbBusinessParams;
  "bbb-business-complaints": BbbBusinessComplaintsParams;
  "bbb-business-more-info": BbbBusinessMoreInfoParams;
  "bbb-business-reviews": BbbBusinessReviewsParams;
  "bbb-category": BbbCategoryParams;
  "bbb-scamtracker-search": BbbScamtrackerSearchParams;
  "bbb-scamtracker-state-stats": BbbScamtrackerStateStatsParams;
  "bbb-scamtracker-detail": BbbScamtrackerDetailParams;
  "bbb-search": BbbSearchParams;
}

export interface OperationResponseMap {
  "bbb-business": BbbBusinessResponse;
  "bbb-business-complaints": BbbBusinessComplaintsResponse;
  "bbb-business-more-info": BbbBusinessMoreInfoResponse;
  "bbb-business-reviews": BbbBusinessReviewsResponse;
  "bbb-category": BbbCategoryResponse;
  "bbb-scamtracker-search": BbbScamtrackerSearchResponse;
  "bbb-scamtracker-state-stats": BbbScamtrackerStateStatsResponse;
  "bbb-scamtracker-detail": BbbScamtrackerDetailResponse;
  "bbb-search": BbbSearchResponse;
}

export interface OperationRequiredParamsMap {
  "bbb-business": true;
  "bbb-business-complaints": true;
  "bbb-business-more-info": true;
  "bbb-business-reviews": true;
  "bbb-category": true;
  "bbb-scamtracker-search": false;
  "bbb-scamtracker-state-stats": false;
  "bbb-scamtracker-detail": true;
  "bbb-search": true;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "bbb-business"
  | "bbb-business-complaints"
  | "bbb-business-more-info"
  | "bbb-business-reviews"
  | "bbb-category"
  | "bbb-scamtracker-search"
  | "bbb-scamtracker-state-stats"
  | "bbb-scamtracker-detail"
  | "bbb-search";

export declare const OperationIds: Readonly<{
  BbbBusiness: "bbb-business";
  BbbBusinessComplaints: "bbb-business-complaints";
  BbbBusinessMoreInfo: "bbb-business-more-info";
  BbbBusinessReviews: "bbb-business-reviews";
  BbbCategory: "bbb-category";
  BbbScamtrackerDetail: "bbb-scamtracker-detail";
  BbbScamtrackerSearch: "bbb-scamtracker-search";
  BbbScamtrackerStateStats: "bbb-scamtracker-state-stats";
  BbbSearch: "bbb-search";
}>;
