// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package bbb

import (
	"context"
	"sort"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"bbb-business":                operationDefinition{Method: "GET", Path: "/bbb/business", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "url", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-business-complaints":     operationDefinition{Method: "GET", Path: "/bbb/business/complaints", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "url", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-business-more-info":      operationDefinition{Method: "GET", Path: "/bbb/business/more-info", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "url", In: "query", Type: "string", Required: true}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-business-reviews":        operationDefinition{Method: "GET", Path: "/bbb/business/reviews", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "url", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-category":                operationDefinition{Method: "GET", Path: "/bbb/category", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "url", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-scamtracker-search":      operationDefinition{Method: "GET", Path: "/bbb/scamtracker/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "query", In: "query", Type: "string"}, parameterDefinition{Name: "scam_type", In: "query", Type: "string", Enum: []string{"Advance Fee Loan", "Bank/Credit Card Company Imposter", "Business Email Compromise", "Charity", "Counterfeit Product", "COVID-19", "Credit Cards", "Credit Repair/Debt Relief", "CryptoCurrency", "Debt Collections", "Employment", "Fake Check/Money Order", "Fake Invoice/Supplier Bill", "Family/Friend Emergency", "Foreign Money Exchange", "Government Agency Imposter", "Government Grant", "Healthcare/Medicaid/Medicare", "Home Improvement", "Identity Theft", "Investment", "Moving", "Online Purchase", "Other", "Phishing", "Rental", "Retail Business", "Romance", "Scholarship", "Sweepstakes/Lottery/Prizes", "Tax Collection", "Tech Support", "Travel/Vacation/Timeshare", "Utility", "Vanity Award", "Worthless Problem-solving Service", "Yellow Pages/Directories"}}, parameterDefinition{Name: "state", In: "query", Type: "string"}, parameterDefinition{Name: "scammer_state", In: "query", Type: "string"}, parameterDefinition{Name: "date_from", In: "query", Type: "string"}, parameterDefinition{Name: "date_to", In: "query", Type: "string"}, parameterDefinition{Name: "min_dollars_lost", In: "query", Type: "integer"}, parameterDefinition{Name: "max_dollars_lost", In: "query", Type: "integer"}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-scamtracker-state-stats": operationDefinition{Method: "GET", Path: "/bbb/scamtracker/state-stats", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "period", In: "query", Type: "string", Enum: []string{"30", "90", "365", "all"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-scamtracker-detail":      operationDefinition{Method: "GET", Path: "/bbb/scamtracker/{id}", PathParams: []string{"id"}, QueryParams: nil, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"bbb-search":                  operationDefinition{Method: "GET", Path: "/bbb/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "query", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "location", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "page", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 9

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// Business calls the bbb-business operation.
func (c *Client) Business(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-business", params)
}

// BusinessComplaints calls the bbb-business-complaints operation.
func (c *Client) BusinessComplaints(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-business-complaints", params)
}

// BusinessMoreInfo calls the bbb-business-more-info operation.
func (c *Client) BusinessMoreInfo(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-business-more-info", params)
}

// BusinessReviews calls the bbb-business-reviews operation.
func (c *Client) BusinessReviews(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-business-reviews", params)
}

// Category calls the bbb-category operation.
func (c *Client) Category(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-category", params)
}

// ScamtrackerSearch calls the bbb-scamtracker-search operation.
func (c *Client) ScamtrackerSearch(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-scamtracker-search", params)
}

// ScamtrackerStateStats calls the bbb-scamtracker-state-stats operation.
func (c *Client) ScamtrackerStateStats(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-scamtracker-state-stats", params)
}

// ScamtrackerDetail calls the bbb-scamtracker-detail operation.
func (c *Client) ScamtrackerDetail(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-scamtracker-detail", params)
}

// Search calls the bbb-search operation.
func (c *Client) Search(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "bbb-search", params)
}
